src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;


    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="like_event")
     */
    private $user_like;

    public function __construct()
    {
        $this->user_like = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUserLike(): Collection
    {
        return $this->user_like;
    }

    public function addUserLike(User $userLike): self
    {
        if (!$this->user_like->contains($userLike)) {
            $this->user_like[] = $userLike;
            $userLike->addLikeEvent($this);
        }

        return $this;
    }

    public function removeUserLike(User $userLike): self
    {
        if ($this->user_like->contains($userLike)) {
            $this->user_like->removeElement($userLike);
            $userLike->removeLikeEvent($this);
        }

        return $this;
    }

}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\DomCrawler\Image;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('image', FileType::class,   [

                'label' => 'Add image',
                'required' => false,
                'data_class' => null,

                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/jpg',
                            'image/png',

                        ],
                        'mimeTypesMessage' => 'Please upload a valid image',
                    ])
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Entity\User;
use App\Form\EventType;
use App\Repository\EventRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/")
 */
class EventController extends Controller
{
    /**
     * @Route("/", name="event_index", methods={"GET"})
     */
    public function index(EventRepository $eventRepository, Security $security, Request $request, EntityManagerInterface $entityManager): Response
    {
        $dql   = "SELECT e FROM App:Event e";
        $query = $entityManager->createQuery($dql);

        $events = $this->get('knp_paginator')->paginate(
        // Doctrine Query, not results
            $query,
            // Define the page parameter
            $request->query->getInt('page', 1),
            // Items per page
            3
        );

        $page = $events->getCurrentPageNumber();
        $user = $security->getUser();


        return $this->render('event/index.html.twig', [
            'events' => $events,
            'user' => $user,
            'page' => $page,
        ]);
    }

    /**
     * @Route("/new", name="event_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {

        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $event = $form->getData();
            $event->setCreatedAt(new \DateTime('now'));

            $user = $this->getUser();
            $event->setUser($user);

            $image = $request->files->get('event')['image'];
            $uploadDirectory = $this->getParameter('upload_directory');


            if ($image) {

                $filename = md5(uniqid()) . '.' . $image->guessExtension();
                $image->move(
                    $uploadDirectory,
                    $filename
                );
                $event->setImage($filename);
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/event/{id}", name="event_show", methods={"GET"})
     */
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }

    /**
     * @Route("/like/{id}", name="event_like", methods={"GET"})
     */
    public function like(Security $security, Event $event, Request $request) : Response
    {
        $user = $security->getUser();

        if (!$event->getUserLike()->contains($user)) {
            $event->addUserLike($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();
        } else {
            $event->removeUserLike($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();
        }

        $page = $request->query->get('page');
        return $this->redirect($this->generateUrl('event_index', ['page' => $page]));
    }

    /**
     * @Route("/edit/{id}", name="event_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Event $event): Response
    {

        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $image = $request->files->get('event')['image'];
            $uploadDirectory = $this->getParameter('upload_directory');

            $event = $form->getData();

            if ($image) {

                $filename = md5(uniqid()) . '.' . $image->guessExtension();

                $image->move(
                    $uploadDirectory,
                    $filename
                );

                $event->setImage($filename);
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="event_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Event $event): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($event);
            $entityManager->flush();
        }
        return $this->redirectToRoute('event_index');
    }

}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/event/_form.html.twig
<div class="mb-3">
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary mb-3">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
</div>

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event{% endblock %}


{% block body %}
    <h1>Edit Event</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}


    <div class="d-flex">
        <a class="btn btn-secondary mr-2" href="{{ path('event_index') }}">back to list</a>
        {{ include('event/_delete_form.html.twig') }}
    </div>

{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('/assets/css/indexEvent.css') }}">
{% endblock %}

{% block body %}
        <h1 class="text-center main-title mb-3">ALL EVENTS</h1>
        {% for event in events %}
            <div class="event-block">
                <div class="row">
                    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                        <div class="like-btn-container">
                            <a class="btn-like {% if ( event.getUserLike.contains(user)) %}active{% endif %}" href="{{ path('event_like', {'id': event.id, 'page': page}) }}"><img src="{{ asset('/assets/img/icons/like.svg') }}" alt="LIKE"></a>
                        </div>
                    {% endif %}
                        <h5 class="like-counter">{{ event.getUserLike.count() }} users liked it</h5>
                    <div class="col-12">
                        <h4 class="text-center">{{ event.title }}</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="event-image-container">
                            <img src="/uploads/{{ event.image ?? 'event_placeholder.png' }}" alt="event">
                        </div>
                    </div>
                </div>
                <div class="row event-data-container">
                    <div class="id-container">
                       № {{ event.id }}
                    </div>
                    <div class="col-6">
                        Created <b>On</b> <i>{{ event.createdAt ? event.createdAt|date('Y-m-d H:i:s') : '' }}</i>
                    </div>
                    <div class="col-6">
                       <b>By</b> &bullet; {{ event.user.login | upper }} &bullet;
                    </div>
                    <div class="action-container">
                            <a class="btn btn-sm btn-info mr-2 mb-2" href="{{ path('event_show', {'id': event.id}) }}">show</a>
                            {% if is_granted('ROLE_ADMIN') %}
                                <a class="btn btn-sm btn-warning mr-2 mb-2" href="{{ path('event_edit', {'id': event.id}) }}">edit</a>
                            {% endif %}
                    </div>
                </div>
            </div>
            {% else %}
                    <div class="row">
                        <div class="col-md-12">no records found</div>
                    </div>
            {% endfor %}

    <div class="row">
        <div class="col-2">
            {% if is_granted('ROLE_ADMIN') %}
                <a class="btn btn-primary my-4" href="{{ path('event_new') }}">Create new</a>
            {% endif %}
        </div>
        <div class="col-10">
            <div class="navigation my-4">
                <div class="float-right">{{ knp_pagination_render(events) }}</div>
            </div>
        </div>
    </div>
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
    <h1 class="text-center">Create new Event</h1>

    {{ include('event/_form.html.twig') }}

    <a class="btn btn-secondary mt-3" href="{{ path('event_index') }}">back to list</a>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('/assets/css/indexEvent.css') }}">
{% endblock %}

{% block body %}
    <h1 class="text-center">Event</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ event.id }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>
                    <div class="event-image-container ml-0">
                        <img src="/uploads/{{ event.image ?? 'event_placeholder.png' }}" alt="event">
                    </div>
                </td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ event.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ event.description }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ event.createdAt ? event.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>User</th>
                <td>{{ event.user.login }}</td>
            </tr>
        </tbody>
    </table>
    <div class="d-flex mb-4">
        <a class="btn btn-secondary mr-2" href="{{ path('event_index') }}">back to list</a>
        {% if is_granted('ROLE_ADMIN') %}
            <a class="btn btn-warning mr-2 edit-btn" href="{{ path('event_edit', {'id': event.id}) }}">edit</a>
            {{ include('event/_delete_form.html.twig') }}
        {% endif %}
    </div>
{% endblock %}